#!/usr/bin/env bash
# Regenerate requirements.lock.txt: one dependency resolution actually tested
# on the shipped runtime.
#
# The lock is resolved inside the same base image the Dockerfile uses
# (python:3.14-slim on linux/amd64), not on a maintainer's laptop, so the
# pinned set is one pip has really installed on the target platform. Run this
# after changing requirements.txt and commit the result.
#
#   scripts/lock_requirements.sh
#
# Requires Docker. Takes a few minutes: it performs a real install.
set -euo pipefail

# Git Bash / MSYS rewrites container-side paths like /tmp/... into Windows
# paths before Docker ever sees them. requirements.txt is piped in on stdin
# rather than bind-mounted for the same reason.
export MSYS_NO_PATHCONV=1

cd "$(dirname "$0")/.."

IMAGE="python:3.14-slim"
OUT="requirements.lock.txt"

echo "Resolving requirements.txt inside ${IMAGE} (linux/amd64)..."

# --no-deps is deliberately absent: we want pip's full transitive resolution.
# The freeze is filtered to drop editable/local entries, which are meaningless
# outside the container.
docker run --rm -i --platform linux/amd64 "${IMAGE}" \
  sh -c '
    set -e
    cat > /tmp/requirements.txt
    apt-get update -qq >/dev/null 2>&1 || true
    apt-get install -y -qq --no-install-recommends gcc >/dev/null 2>&1 || true
    pip install --quiet --upgrade pip >/dev/null
    pip install --quiet --no-cache-dir -r /tmp/requirements.txt >/dev/null
    pip freeze --exclude-editable
  ' < requirements.txt > "${OUT}.tmp"

{
  echo "# Generated by scripts/lock_requirements.sh — do not edit by hand."
  echo "#"
  echo "# A pinned resolution of requirements.txt, produced by really installing"
  echo "# it inside ${IMAGE} on linux/amd64 — the runtime the Docker image ships."
  echo "# Docker and the Linux CI lane install this file so builds are"
  echo "# reproducible; change requirements.txt and re-run the script to update."
  echo "#"
  echo "# Test-only dependencies are NOT here; see requirements-dev.txt."
  echo ""
  sort -f "${OUT}.tmp"
} > "${OUT}"
rm -f "${OUT}.tmp"

echo "Wrote ${OUT} ($(grep -c '==' "${OUT}") pinned packages)."
